# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/HITCS/Computer Design and Practice/exp2/fsm/fsm.cache/wt} [current_project]
set_property parent.project_path {E:/HITCS/Computer Design and Practice/exp2/fsm/fsm.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {e:/HITCS/Computer Design and Practice/exp2/fsm/fsm.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {{E:/HITCS/Computer Design and Practice/exp2/fsm/fsm.srcs/sources_1/new/fsm.vhd}}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top fsm -part xc7a100tcsg324-1


write_checkpoint -force -noxdef fsm.dcp

catch { report_utilization -file fsm_utilization_synth.rpt -pb fsm_utilization_synth.pb }
