# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/HITCS/exp5/cpu/cpu.cache/wt [current_project]
set_property parent.project_path E:/HITCS/exp5/cpu/cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo e:/HITCS/exp5/cpu/cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  E:/HITCS/exp5/cpu/cpu.srcs/sources_1/new/alu.vhd
  E:/HITCS/exp5/cpu/cpu.srcs/sources_1/new/fetch.vhd
  E:/HITCS/exp5/cpu/cpu.srcs/sources_1/new/mod4.vhd
  E:/HITCS/exp5/cpu/cpu.srcs/sources_1/new/ram_ctrl.vhd
  E:/HITCS/exp5/cpu/cpu.srcs/sources_1/new/io_ctrl.vhd
  E:/HITCS/exp5/cpu/cpu.srcs/sources_1/new/refer.vhd
  E:/HITCS/exp5/cpu/cpu.srcs/sources_1/new/write_back.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/HITCS/exp5/cpu/cpu.srcs/constrs_1/imports/other/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files E:/HITCS/exp5/cpu/cpu.srcs/constrs_1/imports/other/Nexys4DDR_Master.xdc]


synth_design -top io_ctrl -part xc7a100tcsg324-1


write_checkpoint -force -noxdef io_ctrl.dcp

catch { report_utilization -file io_ctrl_utilization_synth.rpt -pb io_ctrl_utilization_synth.pb }
