# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/other/Nexys4DDR_Master.xdc

# IP: E:/HITCS/exp5/cpu_artix/ipcore_dir/ddr.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr || ORIG_REF_NAME==ddr}]
